### PR TITLE
make forks run workflows correctly by using pull_request_target

### PR DESCRIPTION
**Pull request by JakeChampion**
origami discussion for this work -- https://github.com/Financial-Times/origami/issues/77

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.3 to 781c9ffc56487ace43440c8ca33f773bb9d49191
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.3 to 9a07e0a5a5f3c84c164ed83dc3323719aa78cf43
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.3 to d5a730ccb82e5fba6d0d7bd3bb36b1dcc1e810c3
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.3 to c4dacc593d863d42a12b2bf78e8932efa2dfd91b
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.3 to 795d1fe70cc1f4c6c9bab72a85593eaff3089f1f
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.3 to 20bc03b1042326219f41831385db765e53b4bb4a
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.3 to c4f1af73ddef34dc3e1ae18af30f0b82a4fd09eb
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.3 to 7223e912dc1bd5241c8691e7fe984a2f04598799
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.3 to 14f443f9248a26934d645f89006b472e105497fb
No significant bundle size differences found.

**Review by chee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.3 to a8122f2229723a09a434b7094b3570ee176babc1
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.4 to 9e2594bc5b68eb22e77fb4a86d936282e2f3bcdc
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-table bundle size difference from 8.1.4 to 3c34b9d2c9d5ad9da94eeb54ca8b6acaeb980655
No significant bundle size differences found.

**Pull request merged**
