### PR TITLE
Remove modifiers

### LINKED ISSUE #28: Remove modifiers demo

### PR DESCRIPTION
**Pull request by j-mes**
Closes #28.

- Remove `modifiers.mustache`.
- Modify `origami.json` to have one entry for JS inside the `demosDefaults` group instead of in each demo group
- Modify `demos.js` to remove JS code for modifiers class switching.

### CODE REVIEW

**Comment by j-mes** [comment]
@SarahHornsey This would remove the modifiers demo which would allow someone to check options via the Registry to see what format of the `o-table` they could have i.e. with stripes, with borders or without and so on.

The use case is that it is not being used enough as seen in #28. What is your opinion on this?

**Comment by SarahHornsey** [comment]
@j-mes Yes, this needs to be removed as we don't want custom stripes and borders, etc.. 
thanks

**Comment by onishiweb** [comment]
@j-mes @SarahHornsey sorry, that's not quite the reason, I should have made the issue a bit more clear.

Currently the modifiers demo allows people to choose how a table displays by adding/removing modifiers. This was discussed in the open meeting that it should not be the case as people should be using a specific style. 

The question is: what is that default style, and what should products be able to change?

**Comment by SarahHornsey** [comment]
@onishiweb The default style is with the border and stripes, which should be a standard feature of the table.

**Comment by onishiweb** [comment]
@SarahHornsey ok so this:

screen shot 2016-06-07 at 11 31 10

should be the default style for all tables

**Comment by SarahHornsey** [comment]
@j-mes Yes, thanks

**Comment by onishiweb** [comment]
Ok, I've created an issue for the default table styles: #34 

@j-mes feel free to merge this one.

👍

**Comment by j-mes** [comment]
Merging away!

**Pull request merged**
